In [2]:
import numpy as np
import os 

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.column_stack((a,b,c))
print(d)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
parent_folder = os.path.join('features','ACF','1hr','clean')
feature_types = ['lag', 'peak', 'zcp']

In [4]:
music_feature_files = [os.path.join(parent_folder, 'music_'+feat+'.txt') for feat in feature_types]
machine_feature_files = [os.path.join(parent_folder, 'machine_'+feat+'.txt') for feat in feature_types]
nature_feature_files = [os.path.join(parent_folder, 'nature_'+feat+'.txt') for feat in feature_types]
speech_feature_files = [os.path.join(parent_folder, 'speech_'+feat+'.txt') for feat in feature_types]

In [5]:
print(music_feature_files)
mus_lag = np.loadtxt(music_feature_files[0])
print(mus_lag.shape)
mus_peak = np.loadtxt(music_feature_files[1])
print(mus_peak.shape)
mus_zcp = np.loadtxt(music_feature_files[2])
print(mus_zcp.shape)
mus_features = np.column_stack((mus_lag, mus_peak, mus_zcp))
print(mus_features.shape)

['features\\ACF\\1hr\\clean\\music_lag.txt', 'features\\ACF\\1hr\\clean\\music_peak.txt', 'features\\ACF\\1hr\\clean\\music_zcp.txt']
(720511,)
(720511,)
(720511,)
(720511, 3)


In [6]:
print(machine_feature_files)
mac_lag = np.loadtxt(machine_feature_files[0])
print(mac_lag.shape)
mac_peak = np.loadtxt(machine_feature_files[1])
print(mac_peak.shape)
mac_zcp = np.loadtxt(machine_feature_files[2])
print(mac_zcp.shape)
mac_features = np.column_stack((mac_lag, mac_peak, mac_zcp))
print(mac_features.shape)

['features\\ACF\\1hr\\clean\\machine_lag.txt', 'features\\ACF\\1hr\\clean\\machine_peak.txt', 'features\\ACF\\1hr\\clean\\machine_zcp.txt']
(720511,)
(720511,)
(720511,)
(720511, 3)


In [7]:
print(nature_feature_files)
nat_lag = np.loadtxt(nature_feature_files[0])
print(nat_lag.shape)
nat_peak = np.loadtxt(nature_feature_files[1])
print(nat_peak.shape)
nat_zcp = np.loadtxt(nature_feature_files[2])
print(nat_zcp.shape)
nat_features = np.column_stack((nat_lag, nat_peak, nat_zcp))
print(nat_features.shape)

['features\\ACF\\1hr\\clean\\nature_lag.txt', 'features\\ACF\\1hr\\clean\\nature_peak.txt', 'features\\ACF\\1hr\\clean\\nature_zcp.txt']
(720511,)
(720511,)
(720511,)
(720511, 3)


In [8]:
print(speech_feature_files)
spe_lag = np.loadtxt(speech_feature_files[0])
print(spe_lag.shape)
spe_peak = np.loadtxt(speech_feature_files[1])
print(spe_peak.shape)
spe_zcp = np.loadtxt(speech_feature_files[2])
print(nat_zcp.shape)
spe_features = np.column_stack((spe_lag, spe_peak, spe_zcp))
print(spe_features.shape)

['features\\ACF\\1hr\\clean\\speech_lag.txt', 'features\\ACF\\1hr\\clean\\speech_peak.txt', 'features\\ACF\\1hr\\clean\\speech_zcp.txt']
(755621,)
(755621,)
(720511,)
(755621, 3)


In [9]:
mus_len = mus_lag.shape[0]
nat_len = nat_lag.shape[0]
spe_len = spe_lag.shape[0]
mac_len = mac_lag.shape[0]
print(mac_len)

720511


In [ ]:
# mac_labels = np.zeros((mac_len,1), dtype=np.int8)
# mus_labels = np.ones((mus_len,1), dtype=np.int8)
# nat_labels = 3 * np.ones((nat_len,1), dtype=np.int8)
# spe_labels = 2 * np.ones((spe_len,1), dtype=np.int8)
# print(spe_labels.shape)
# acf_feats = np.vstack((mac_features, mus_features, spe_features, nat_features))
# acf_labels = np.vstack((mac_labels, mus_labels, spe_labels, nat_labels))
# print(acf_feats.shape)
# print(acf_labels.shape)
#print(acf_feats[:10, :])
#rand_idx = np.random.choice(np.arange(acf_feats.shape[0]), size=acf_feats.shape[0], replace=False)
# acf_feats = acf_feats[rand_idx, :]
# acf_labels = acf_labels[rand_idx, : ]
# train_test_split = 0.8
# split_idx = int(train_test_split * acf_feats.shape[0])
# print(split_idx)
# train_set = acf_feats[:split_idx, :]
# test_set = acf_feats[split_idx:, :]
# train_labels = acf_labels[:split_idx, :]
# test_labels = acf_labels[split_idx:, :]
# print(train_set.shape)
# print(train_labels.shape)
# print(test_set.shape)
# print(test_labels.shape)
# np.savetxt('acf_train.csv', train_set)
# np.savetxt('acf_train_labels.csv', train_labels)
# np.savetxt('acf_test.csv', test_set)
# np.savetxt('acf_test_labels.csv', test_labels

In [10]:
# 0 -> speech + music, 1-> nature + machine
spe_mus_labels = np.zeros((spe_len+mus_len,1), dtype=np.int8)
nat_mac_labels = np.ones((nat_len+mac_len, 1), dtype=np.int8)
#0 ->  speech 1-> music 2-> nature 3-> machine
spe_labels = np.zeros((spe_len,1), dtype=np.int8)
mus_labels = np.ones((mus_len,1), dtype=np.int8)
nat_labels = np.full((nat_len,1), 2, dtype=np.int8)
mac_labels = np.full((mac_len,1), 3, dtype=np.int8)

In [11]:
two_class_acf_feats = np.vstack((spe_features, mus_features, nat_features, mac_features))
two_class_acf_labels = np.vstack((spe_mus_labels, nat_mac_labels))
four_class_acf_labels = np.vstack((spe_labels, mus_labels, nat_labels, mac_labels))
print(two_class_acf_feats.shape)
print(two_class_acf_labels.shape)
print(four_class_acf_labels.shape)

(2917154, 3)
(2917154, 1)
(2917154, 1)


In [11]:
print(two_class_acf_labels[19995:20005])

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [12]:
rand_idx = np.random.choice(np.arange(two_class_acf_feats.shape[0]), size=two_class_acf_feats.shape[0], replace=False)
two_class_acf_feats = two_class_acf_feats[rand_idx, : ]
two_class_acf_labels = two_class_acf_labels[rand_idx, : ]
four_class_acf_labels = four_class_acf_labels[rand_idx, :]

In [13]:
train_test_split = 0.9
split_idx = int(train_test_split * two_class_acf_feats.shape[0])
print(split_idx)
train_set = two_class_acf_feats[:split_idx, :]
test_set = two_class_acf_feats[split_idx:, :]
train_labels = two_class_acf_labels[:split_idx, :]
test_labels = two_class_acf_labels[split_idx:, :]
test_deep_labels = four_class_acf_labels[split_idx:, :]

2625438


In [29]:
print(train_labels.shape)
print(train_deep_labels.shape)
print(train_set.shape)
print(test_labels.shape)
print(test_set.shape)
print(train_labels[20:30])
print(test_deep_labels[20:30])

(2625438, 1)
(2625438, 1)
(2625438, 3)
(291716, 1)
(291716, 3)
[[1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]
[[3]
 [2]
 [2]
 [0]
 [2]
 [3]
 [2]
 [0]
 [3]
 [0]]


In [14]:
dest_path = os.path.join('sets_labels','ACF','1hr', 'clean')

In [15]:
np.savetxt(os.path.join(dest_path, 'train_set_v3.csv'), train_set)
np.savetxt(os.path.join(dest_path,'train_labels_v3.csv'), train_labels)
np.savetxt(os.path.join(dest_path,'test_set_v3.csv'), test_set)
np.savetxt(os.path.join(dest_path,'test_labels_v3.csv'), test_labels)
np.savetxt(os.path.join(dest_path,'test_deep_labels_v3.csv'), test_deep_labels)

In [ ]:
print(two_class_acf_labels[:10])

In [ ]:
x = np.array([12,2,9,5,4,1,3,7,11,3,6])
print(np.argmax(x[2:]))

In [33]:
from sklearn.metrics import confusion_matrix
y_true = [2, 0, 1, 2, 2, 3]
y_pred = [0, 0, 1, 1, 0, 1]
confusion_matrix(y_true, y_pred)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [2, 1, 0, 0],
       [0, 1, 0, 0]], dtype=int64)